Update XenonCI2.yml

diff --git a/.github/workflows/XenonCI2.yml b/.github/workflows/XenonCI2.yml
--- a/.github/workflows/XenonCI2.yml
+++ b/.github/workflows/XenonCI2.yml
@@ -1,23 +1,31 @@
-name: GSI-Workshop2
+me: GSI-Workshop2
 
 on:
- workflow_dispatch:
-    
-env:
-  ROM_URL: https://otafsg1.h2os.com/patch/amazone2/GLO/NordOxygen/NordOxygen_14.O.10_GLO_010_2009260504/NordOxygen_14.O.10_OTA_010_all_2009260504_113aafee5.zip
-  ROM_NAME: OxygenOS
-  ZIP_NAME: OxygenOS-GSI-Workshop
-  TZ: Asia/Dhaka
-  MIR: wet
+  workflow_dispatch:
+
+defaults:
+  run:
+    shell: bash
+
 jobs:
   build:
     runs-on: ubuntu-latest
-
-
     steps:
-       - name: Checkout
-         uses: actions/checkout@master
-           
+      - name: Checkout
+        uses: actions/checkout@v2
+      - name: Load Configuration
+        uses: falti/dotenv-action@v0.2.5
+        id: config
+        with:
+          path: config2.env
+      - name: Check Configuration
+        run: |
+          function required () { if ! [[ "$1" ]]; then echo "$2 variable can't be null." && exit 1; fi }
+          required "${{ steps.config.outputs.url }}" "URL config"
+          required "${{ steps.config.outputs.rom_type }}" "ROM_TYPE config"
+          required "${{ steps.config.outputs.zip_name }}" "ZIP_NAME config"
+          required "${{ steps.config.outputs.mir }}" "MIR config"
+        
        - name: Initializing environment
          run: |
             sudo -E apt-get -qq update
